### ISSUE TITLE
SHSearchBar can be used in tableview

### ISSUE THREAD

**Issue by pdgoyal** [Blackjacx/SHSearchBar#43]
Hi! I am new in swift. I want to use this pod for my project. How can I use this pod in searching data inside UITableView? Thank you

**Comment by Blackjacx** [comment]
Hey, good news for you! I have another library which searches (offline) data in a UITableView. Everything is implemented in this class: https://github.com/Blackjacx/Columbus/blob/develop/Columbus/Classes/CountryPickerViewController.swift 

Just use my SHSearchBar instead of the native UISearchBar I used there (I want to have no dependencies). It is my newest lib so everything is up-to-date.

**Comment by CobraAI** [comment]
This issue will be closed due to **inactivity**. Please open a new issue if your problem still exists.
