### ISSUE TITLE
please keep cocoapods

### ISSUE THREAD

**Issue by jafara** [Blackjacx/SHSearchBar#57]
i still use it and I dont want to use spm

**Comment by Blackjacx** [comment]
Hey, sorry to switch over to SPM. You should try it. We also use all 3
dependency manager in parallel and it works great. I must say the
experience with SPM is really the best. You should try it as long as you
haven’t any hard requirements against.

Cheers 🥃
-- 

Viele Grüße

Stefan Herold

Mobile Software Engineer a.d. 2009

E-Mail stefan.herold@gmail.com

Web www.stefan-herold.net

**Comment by Blackjacx** [comment]
I'll close this issue since SPM will be the future imho and this has been mentioned even by the Carthage developers. 

One tip foud you @jafara you can easily get the code from the latest working version and integrate it into your repo. It is not so much 👍 

Thank you all for using my mini framework 👍
